exercise_mappings = {
        'Barbell Flat Bench Press': 'Bench Press (Barbell)',
        'Barbell Deadlift': 'Deadlift (Barbell)',
        'Barbell Squats (standing)': 'Squat (Barbell)',
        'Barbell Shoulder Press (standing)': 'Overhead Press (Barbell)',
        'Machine Leg Extension (seated)': 'Leg Extension (Machine)',
        'Machine Calf Raise (standing)': 'Standing Calf Raise (Machine)',
        'Crosstrainer (Elliptical)': 'Elliptical Trainer',
        'Machine Fly (seated)': 'Chest Fly (Machine)',
        'Pulley Machine Triceps Press (standing)': 'Triceps Pushdown',
        'Overhead Pulley Machine Triceps Rope Press (standing)': 'Triceps Extension (Cable)',
        'Machine Front Press (seated)': 'Chest Press (Machine)',
        'Dumbbell Bench Press (incline)': 'Incline Bench Press (Dumbbell)',
        'Reverse Machine Flys (seated)': 'Rear Delt Reverse Fly (Machine)',
        'Pulley Machine Row (seated)': 'Seated Cable Row - V Grip (Cable)',
        'Pulley Machine Pulldown To Chest, Wide Grip (seated)': 'Lat Pulldown (Cable)',
        'EZ-Bar Biceps Curl (standing)': 'EZ Bar Biceps Curl',
        'Romanian Deadlift': 'Romanian Deadlift (Barbell)',
        'Smith Machine Calf Raise (standing)': 'Standing Calf Raise (Machine)',
        'Dumbbell Biceps Hammer Curl (seated)': 'Hammer Curl (Dumbbell)',
        'Stationary Cycling': 'Spinning',
        'Machine Leg Curl (seated)': 'Seated Leg Curl (Machine)',
        'Machine Leg Press (incline)': 'Leg Press (Machine)',
        'Dumbbell Shoulder Press (seated)': 'Shoulder Press (Dumbbell)',
        'Machine Shoulder Press (seated)': 'Seated Shoulder Press (Machine)',
        'Leverage Machine Row (seated)': 'Seated Row (Machine)',
        'Machine Hyperextensions (seated)': 'Back Extension (Machine)',
        'Dumbbell Row, Bent Over (standing)': 'Bent Over Row (Dumbbell)',
        'Dumbbell Biceps Hammer Curl (standing)': 'Hammer Curl (Dumbbell)',
        'Machine Leg Curl (standing)': 'Seated Leg Curl (Machine)',
        'Dumbbell Front Raise (standing)': 'Front Raise (Dumbbell)',
        'Straight Arm Pulley Machine Push Down (standing)': 'Straight Arm Lat Pulldown (Cable)',
        'Machine Crunch (seated)': 'Crunch (Machine)',
        'Pulley Machine Rope Triceps Press (standing)': 'Triceps Rope Pushdown',
        'Hip Thrust': 'Hip Thrust (Barbell)',
        'Machine Leg Curl (prone)': 'Lying Leg Curl (Machine)',
        'Rowing': 'Rowing Machine',
        'Machine Flat Bench Press': 'Chest Press (Machine)',
        'Machine Lateral Raise (seated)': 'Lateral Raise (Machine)',
        'Dumbbell Flat Bench Press': 'Bench Press (Dumbbell)',
        'Pulley Machine Crossover (standing)': 'Cable Fly Crossovers',
        'Machine Bench Press (incline)': 'Incline Chest Press (Machine)',
        'Dumbbell Biceps Curl (seated)': 'Bicep Curl (Dumbbell)',
        'Leverage Machine Pulldown (seated)': 'Lat Pulldown (Machine)',
        'Pulley Machine Biceps Curl (standing)': 'Bicep Curl (Cable)',
        'Machine Calf Raise (seated)': 'Calf Press (Machine)',
        'Machine Squats (incline)': 'Squat (Machine)',
        'Pulley Machine Rope Biceps Curl (standing)': 'Rope Cable Curl',
        'Leg Raise, Rest On Arms': 'Leg Raise Parallel Bars',
        'Scott Machine EZ-Bar Biceps Curl (seated)': 'Preacher Curl (Barbell)',
        'Pulley Machine Rope Pull Through (standing)': 'Cable Pull Through',
        'Barbell Row, Bent Over (standing)': 'Bent Over Row (Barbell)',
        'Knee Raise (hanging)': 'Hanging Knee Raise',
        'Single Arm Pulley Machine Lateral Raise (bent over)': 'Single Arm Lateral Raise (Cable)',
        'Push-ups, Wide Grip': 'Push Up',
        'Dumbbell Lateral Raise (standing)': 'Lateral Raise (Dumbbell)',
        'Nordic Curl': 'Nordic Hamstrings Curls',
        'Smith Machine Bench Press (incline)': 'Incline Bench Press (Smith Machine)',
        'Dumbbell Biceps Curl (incline)': 'Bicep Curl (Dumbbell)',
        'Pulley Machine Crunches (seated)': 'Cable Crunch',
        'Leg Raise (hanging)': 'Hanging Leg Raise',
        'Leg Raise (lying)': 'Lying Leg Raise',
        'Reverse Crunches': 'Reverse Crunch',
        'Pulley Machine Pulldown To Chest, Hammer Close Grip (seated)': 'Lat Pulldown - Close Grip (Cable)',
        'Low Pulley Machine Crossover (standing)': 'Low Cable Fly Crossovers',
        'Barbell Biceps Curl (standing)': 'Bicep Curl (Barbell)',
        'Machine Hyperextensions': 'Back Extension (Machine)',
        'Reverse Crunches, Raised Legs': 'Reverse Crunch',
        'Barbell Bench Press (incline)': 'Incline Bench Press (Barbell)',
        'Dumbbell Deadlift': 'Deadlift (Dumbbell)',
        'Single Leg Press': 'Single Leg Press (Machine)',
        'Dumbbell Biceps Curl (standing)': 'Bicep Curl (Dumbbell)',
        'Pull-ups, Underhand Close Grip': 'Chin Up',
        'Leg Kickback (kneeling)': 'Glute Kickback (Machine)',
        'Machine Triceps Press (seated)': 'Triceps Extension (Machine)',
        'Crunches (decline)': 'Decline Crunch',
        'Smith Machine Front Squats (standing)': 'Squat (Smith Machine)',
        'Flat Bench Hyperextensions (prone)': 'Back Extension (Hyperextension)',

        # Assume single arm for these
        'Cable Lateral Raise (standing)': 'Single Arm Lateral Raise (Cable)',
        'Cable Lateral Raise': 'Single Arm Lateral Raise (Cable)',

        # Assume weighted for these
        'Pull-ups, Overhand Medium Grip': 'Pull Up (Weighted)',
        'Bar Dips': 'Chest Dip (Weighted)',

        # Mappings to custom exercise name
        'Pulley Machine Row, Bent Over (standing)': 'Bent Over Row (Cable)',
        'Barbell Flat High Bench Row (prone)': 'Seal Row (Barbell)',
        'Single Arm Pulley Machine Front Raise (standing)': 'Single Arm Front Raise (Cable)',
        
        # Mappings with same name
        'Bulgarian Split Squat': 'Bulgarian Split Squat',
        'Running': 'Running',
        'Rack Pull': 'Rack Pull',

        # This mapping may be incomplete so please ensure to 
        # add all other mappings you need based on on your data
    }

